### PR TITLE
 Rename kate to kirito 

### PR DESCRIPTION
**Pull request by iSasuke7**
Dual Plugins is a unique skill that belongs to Kiritoborg in Durov Online.

You need this skill to be able to survive in the harsh World of Durov.

### CODE REVIEW

**Comment by iSasuke7** [comment]
What does 👍 mean?

Please merge ^.^

**Comment by udf** [comment]
# no

**Comment by Lonami** [comment]
# Please merge this. We need this change.

**Comment by udf** [comment]
no u

**Comment by Lonami** [comment]
# :(

**Pull request closed without merging**
